version: '2'
services:
  ros-neonavigation:
    image: "neonavigation-shadow-fixed:${ROS_DISTRO}"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    devices:
      - "/dev/dri:/dev/dri"
    environment:
      DISPLAY: ":0"
