FROM ros:kinetic-ros-core

SHELL ["bash", "-c"]

RUN apt-get update -qq \
  && apt-get install -y wget \
  && apt-get clean && rm -rf /var/lib/apt/list/*

RUN echo "deb http://packages.ros.org/ros-shadow-fixed/ubuntu `lsb_release -sc` main" > /etc/apt/sources.list.d/ros-latest.list \
  && rosdep update

COPY package.xml /ws/src/self/

ARG NEONAVIGATION_VERSION="0.2.0"
RUN cd /tmp \
  && wget -q https://github.com/at-wat/neonavigation/archive/${NEONAVIGATION_VERSION}.tar.gz \
  && tar xzfv ${NEONAVIGATION_VERSION}.tar.gz \
  && cat /ws/src/self/package.xml | grep depend | sed -s "s/\s*//g" | sed -s "s/<[^<]*>//g" | while read pkg; do [ -d neonavigation-${NEONAVIGATION_VERSION}/$pkg ] && echo $pkg || true; done | tee /ws/deps \
  && cat /ws/deps | xargs -n1 -i mv neonavigation-${NEONAVIGATION_VERSION}/{} /ws/src/ \
  && cd /ws \
  && apt-get update -qq \
  && rosdep install -y --from-paths src --ignore-src \
  && apt-get clean && rm -rf /var/lib/apt/list/* \
  && source /opt/ros/${ROS_DISTRO}/setup.bash \
  && catkin_make_isolated --install --install-space /opt/ros/${ROS_DISTRO} --cmake-args -DCMAKE_BUILD_TYPE=Release \
  && rm -rf src/* devel_isolated build_isolated

COPY . /ws/src/self

RUN apt-get update -qq \
  && cd /ws \
  && rosdep install -y --from-paths src --ignore-src --skip-keys "`cat /ws/deps`" \
  && apt-get clean && rm -rf /var/lib/apt/list/* \
  && source /opt/ros/${ROS_DISTRO}/setup.bash \
  && catkin_make_isolated --install --install-space /opt/ros/${ROS_DISTRO} --cmake-args -DCMAKE_BUILD_TYPE=Release
